version: "1"

services:
  - type: web
    name: cloudgram-monolith
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PORT
        value: 10000
      - key: START_KEEP_ALIVE
        value: "true"
      # Recuerda agregar DATABASE_URL, TELEGRAM_BOT_TOKEN, etc. manualmente en Render
