version: "1"

services:
  - type: web
    name: cloudgram-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_admin:app
    envVars:
      - key: PORT
        value: 10000
      # Recuerda agregar DATABASE_URL manualmente en el panel de Render hacia tu Supabase

  - type: worker
    name: cloudgram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars: []
      # Recuerda agregar DATABASE_URL manualmente en el panel de Render hacia tu Supabase
